"""add_food_catalog

Revision ID: ef66758fe048
Revises: 54c0e1fe0fec
Create Date: 2026-02-22 22:09:01.184488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef66758fe048'
down_revision: Union[str, None] = '54c0e1fe0fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normal_macros', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('nutrition_logs', sa.Column('food_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'nutrition_logs', 'food_catalog', ['food_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nutrition_logs', type_='foreignkey')
    op.drop_column('nutrition_logs', 'food_id')
    op.drop_table('food_catalog')
    # ### end Alembic commands ###
